# Generated by Django 4.2.3 on 2023-11-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Catagory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("tech", "tech"),
                            ("soccer", "soccer"),
                            ("game", "game"),
                            ("movies", "movies"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
