# Generated by Django 4.2.3 on 2023-11-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="my cute blog", max_length=300),
        ),
    ]
