# Generated by Django 4.2.3 on 2023-11-05 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_catagory"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="catagory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogapp.catagory",
            ),
            preserve_default=False,
        ),
    ]
