# Generated by Django 4.2.3 on 2023-11-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0003_post_catagory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catagory",
            name="name",
        ),
        migrations.AlterField(
            model_name="post",
            name="catagory",
            field=models.CharField(max_length=5),
        ),
    ]
