# Generated by Django 4.2.3 on 2023-11-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_post_catagories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="catagories",
            field=models.CharField(
                choices=[
                    ("tech", "tech"),
                    ("soccer", "soccer"),
                    ("poletics", "poletics"),
                    ("movies", "movies"),
                ],
                max_length=200,
            ),
        ),
    ]
