# Generated by Django 4.2.3 on 2023-11-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0005_remove_post_catagory"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="catagory",
            field=models.CharField(
                choices=[
                    ("tech", "tech"),
                    ("soccer", "soccer"),
                    ("game", "game"),
                    ("movies", "movies"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
