# Generated by Django 4.2.3 on 2023-11-05 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogapp", "0006_post_catagory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lazy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nottitle", models.CharField(max_length=100)),
                ("nottitle_tag", models.CharField(max_length=100)),
                ("notbody", models.TextField()),
                ("notpost_date", models.DateField(auto_now_add=True)),
                (
                    "notcatagory",
                    models.CharField(
                        choices=[
                            ("tech", "tech"),
                            ("soccer", "soccer"),
                            ("game", "game"),
                            ("movies", "movies"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "notauthor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Catagory",
        ),
    ]
