# Generated by Django 4.2.3 on 2023-11-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0007_lazy_delete_catagory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lazy",
            name="notauthor",
        ),
        migrations.RemoveField(
            model_name="lazy",
            name="notbody",
        ),
        migrations.RemoveField(
            model_name="lazy",
            name="notcatagory",
        ),
        migrations.RemoveField(
            model_name="lazy",
            name="notpost_date",
        ),
    ]
