# Generated by Django 4.2.3 on 2023-11-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0008_alter_post_catagories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="catagories",
        ),
        migrations.AddField(
            model_name="catagory",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
