# Generated by Django 4.2.3 on 2023-11-08 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogapp", "0011_rename_like_post_likes_delete_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="unlike",
            field=models.ManyToManyField(
                related_name="unlike_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
