# Generated by Django 4.2.3 on 2023-11-10 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0012_post_unlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="snippets",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
