# Generated by Django 4.2.3 on 2023-11-12 03:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0013_post_snippets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="unlike",
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="snippets",
            field=models.TextField(),
        ),
    ]
