# Generated by Django 4.2.3 on 2023-11-12 03:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blogapp", "0014_remove_post_unlike_alter_post_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="unlike",
            field=models.ManyToManyField(
                related_name="unlike_user", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="snippets",
            field=models.CharField(max_length=255),
        ),
    ]
