# Generated by Django 4.2.3 on 2023-11-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0017_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/userprofile/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
