# Generated by Django 4.2.3 on 2023-11-09 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_custemuser_delete_pasta"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustemUser",
        ),
    ]
